### ISSUE TITLE
Demo de las funciones creadas 

### ISSUE THREAD

**Issue by NadiaMorales** [AyitaXD/Library#17]
Aplicar en el index las clases creadas con JS para mostrar su funcionalidad.

**Comment by NadiaMorales** [comment]
Agregue la clase zoom que agranda las imagenes

**Comment by keslymartinez** [comment]
Agregue las tallas de la imagenes en js y el Index.

**Comment by NadiaMorales** [comment]
se creo la rama Demo donde va el la web de prueba que muestra las funciones de la lbreria y se publico en gh-pages
